languageCode = "en-us"
baseURL = "https://sscode.top"
title = "Shengli's Blog"
theme = "hugo-cards"
themesDir = "./themes"
paginate = 6

[params]
  defaultImage = "gopher.jpg"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "shengli"
     link = "https://github.com/shenglig"
