name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          submodles: true
      - name: download hugo
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          hugo-version: 'latest'
      - name: build
        run: hugo 
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secerts.ACCESS_TOKEN }}
          PUBLIC_BRANCH: gh-pages
          PUBLIC_DIR: ./public      
